spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 2000
    url: jdbc:mysql://mysql:3306/user_service
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev:dev@discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 3
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
