server:
  port: 8081

spring:
  profiles:
    default: dev-group
    group:
      dev-group:
        - dev
        - dev-local
      prod-group:
        - prod
        - prod-local
  application:
    name: identity-service
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  flyway:
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

app:
  auth:
    email-verification-otp-time: 300 # seconds
    email-verification-otp-length: 6
    access-token-time: 3600 # seconds
    refresh-token-time: 604800 # seconds
