spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev:dev@discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 3
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
  