server:
  port: 8080

spring:
  profiles:
    default: dev-group
    group:
      dev-group:
        - dev
        - dev-local
      prod-group:
        - prod
        - prod-local
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
