CREATE TABLE `users` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `identifier` VARCHAR(150) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `identity_type` ENUM('EMAIL') NOT NULL,
    `status` ENUM('PENDING', 'ACTIVE', 'DISABLED', 'BANNED') DEFAULT 'PENDING',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
