spring:
  security:
    user:
      name: dev
      password: dev

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 0
