server:
  port: 8761

spring:
  profiles:
    default: dev-group
    group:
      dev-group:
        - dev
        - dev-local
      prod-group:
        - prod
        - prod-local
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
